### ISSUE TITLE
Support .csv file format

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#184]
BIDS is pretty clear that all tabular data have to be in the `.tsv` tab delimited format: https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#tabular-files

```
Tabular data MUST be saved as tab delimited values (.tsv) files, that is, CSV files where commas are replaced by tabs. Tabs MUST be true tab characters and MUST NOT be a series of space characters.
```

In practice, people don't always follow the spec or we don't always encounter true BIDS datasets - and so the tabular files are often `.csv` instead. We have two options here:

- be strict about the file format and handle the "whoops, I thought this was a .tsv" route with validation and erroring
- be not strict and internally convert / handle both formats.

![Image](https://user-images.githubusercontent.com/1302022/187727013-16459927-456b-44fc-a970-5cd5441ddbe0.png)

**Comment by jarmoza** [comment]
I'd go with your instinct on this one given you've experienced more BIDS datasets than I have in the field. 

I can tell you that from a software engineering perspective letting the user get away with bad data is usually a no-no – because where does incorporating that into your design end? However, like much else in life sometimes the broken rule becomes the norm and we don't want to turn away users with 'bad' BIDS data formatting.

My gut says let's support both csv and tsv formats.

**Comment by surchs** [comment]
Closing this now as not a priority.
