### ISSUE TITLE
Find a way to keep package.json versions up to date

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#294]
Our dependencies are pretty outdated (e.g. https://github.com/neurobagel/annotation_tool/issues/293), there hasn't been an update to them in a while. We should 

- [ ] research ways to keep the package.json up to date
- [ ] discuss the options with the team and make a decision
- [ ] document the process necessary to update dependencies

This isn't about implementing the update, this is about finding a good solution for the general problem of "all my JS dependencies are old now".

**Comment by jarmoza** [comment]
I have been tempted to keep these up to date. Perhaps looking outward would be best for an answer here. 

The best reason is likely not updating for the sake of updating, but rather because updates occasionally also include security patches – something that our userbase would likely be interested in depending on the deployment implementation of the annotation tool and other tools in the Neurobagel suite.

**Comment by surchs** [comment]
Yes, fully agree. There is dependabot (e.g. [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions)) that I've seen several projects use for automatic version bumping in response to security patches. Maybe that's a way to start? But let's collect some ideas here.

**Comment by surchs** [comment]
Closing as duplicate of #88
