### ISSUE TITLE
Refactoring the store to use the data dictionary: Phase 2

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#305]
With phase 1 (#251) of the store refactor done, we now focus on getting the getters, mutations, and actions for the annotation part of the app updated.

## Resources:

[Here is a great blog post](https://dev.to/bahmutov/unit-testing-vuex-data-store-using-cypress-io-test-runner-3g4n) by one of the cypress maintainers on how to unit-test, mock, stub, etc Vuex methods. 

There are also some examples for these unit tests in our wiki now: https://github.com/neurobagel/documentation/wiki/Cypress-Test-Snippets

## Completion checklist

Every implemented method should have:

1. the method implemented in the correct section (getter, mutation, ...) in the store
2. all necessary state variables that the method relies on are initialized in the state (i.e. defined, not assigned real data) 
3. unit test(s) that test the core functionality of the method (required state variables in the store and any other needed inputs should be mocked)
4. any component that depends on this method existing ([check miro board](https://miro.com/app/board/uXjVP8wIUms=/?share_link_id=577947271587) and codebase) is checked to make sure it is calling the new method by the correct name and is refactored (including its component tests) where necessary to do so

## Phase 2 - everything after the categorization page

ready
- [x] #341
- [x] #352 
- [x] #268 

need review

- [x] #347 
- [x] #348 

done

- [x] #336 
- [x] #272 
- [x] #270
- [x] #276 
- [x] #266 
- [x] #267 
- [x] #338 
- [x] #271 
- [x] #273
- [x] #300
- [x] #275 
- [x] #278 
- [x] #277 
- [x] #274

**Comment by jarmoza** [comment]
Going to add a task list for @rmanaem here.

As of today, here is what is outstanding with phase 2 of the store refactor

**Small, Independent Tasks**

- [ ] #268 
This json output has begun to be well described in the issue. @surchs Has provided an example files.
- [ ] #274 
This will likely require a new field in the column entries of store field a map between raw values and annotated values in  `dataDictionary.annotated.<column_name>`. The field has yet been specified on the [Miro board store draft](https://miro.com/app/board/uXjVP8wIUms=/), though the mutation itself has been: `selectAnOption`.

**Transformation Heuristics for Continuous Values and Options for Categorical Values**

- [ ] #272 
For the time being we are going to be essentially transferring the continuous value transformation code from the previous version of the annotation tool. (See `annot-age-values` utility functions `convertAge`, `detectAge`, etc.)

- [ ] #336 
We want to give the ability for columns that have the continuous values data type to individually change their transformation heuristic. This involves a new UI feature as well as altering the transformation heuristic-related functions to accept columns instead of categories.

**Comment by surchs** [comment]
@jarmoza: I just noticed that we're using the `getSelectedOption` getter in the `annot-categorical` component to populate the dropdown with the currently selected term ([see here](https://github.com/neurobagel/annotation_tool/blob/28854e8c5d5f4e437301df8f90bf1a7c739bff04/components/annot-categorical.vue#L26)). This getter isn't implemented in the store yet, and I can't find an issue for it. Maybe we just forgot this guy? Mind taking a look to confirm it's missing? I could take care of it together with #371.

**Comment by jarmoza** [comment]
@surchs Yes! We forgot it. I noticed this as well during the work I've been doing though I was going to address it in a later PR. I currently have the annotation page functioning without this function. In my view`getSelectedOption` essentially is the solution to the field wipe bug in that `getSelectedOption` retrieves what's been stored for the original value in `datDictionary.annotated`.

Are you sure you meant #371? Maybe you had a different idea of what this getter should do.

**Comment by jarmoza** [comment]
Closed by #437
