### ISSUE TITLE
can we launch a partially complete app

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#308]
With #251 done, the app should now partially work again - at least up to the categorization page. Here we want to make sure that:

- [ ] we can launch the app even though part of it relies on not-yet-implemented store methods (e.g. annotation page)
- [ ] OR: understand how we can partially launch the app in the state it is in now

This can be closed when the current app state can be successfully launched via `npm run dev` locally, even if the UI or functionality doesn't work correctly yet.

**Comment by jarmoza** [comment]
To briefly comment on the work on this issue in branch [jarmoza-308](https://github.com/neurobagel/annotation_tool/tree/jarmoza-308), the goal of this task needs to be amended to have most of the primary functionality be complete from index page to the categorization page in order to move on to refactoring the e2e tests for those pages.

The subtasks for #308 are as follows:

- [ ] Functional index page (uploading data table and data dictionary, ensuring categorization page access requirements are updated)
- [ ] Functional navbar and next page buttons - updated for the store refactor
- [ ] Functional categorization page with working `category-select-table` and `column-linking-table` to enable access to the annotation page

**Comment by jarmoza** [comment]
At the beginning of this work re: PR #318, the tool was not loading in the browser because the old store `index.js` did not mesh up with the code for the landing page and its components.

This was initially overcome via [Unit test imports changed to index.js](https://github.com/neurobagel/annotation_tool/pull/318/commits/62e6ba8ac68ceb0d7c5afdb3891cb3791ceedabc), [Index.js refactor file swap + initial changes](https://github.com/neurobagel/annotation_tool/pull/318/commits/55fe94af833b6100bafc6c3d5d047c5513a92951),

**Comment by jarmoza** [comment]
Closed by #327
