### ISSUE TITLE
Data dictionary loading requires case-sensitive keys - causing issue on landing/categorization pages

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#316]
With the phase 1 refactor, we have changed the data dictionary so that 1) a skeleton dictionary is loaded with every new data table, and 2) if a data dictionary is selected, it augments the current data dictionary (either blank or not) and does not add any new fields.

One issue that has arisen is that since JavaScript is a case-sensitive language, the capitalization for keys in the data dictionary (e.g. a BIDS-style data dictionary) matter. For example, 'description' does not match up with 'Description.`

1. Since the default skeleton dictionary contains an empty `'description` key for each column, any loading (remember, augmentation) of a further data dictionary with the lowercase 'd' will not overwrite that entry but instead add another (i.e. 'Description).
2. This causes the effect of the `column-linking-table` on the categorization page to not have visible descriptions.

What should be done?

Let's agree to data dictionary string normalization rules.

**Comment by surchs** [comment]
Oh, that's a great point! I am actually not completely sure if BIDS requires these keys to be capitalized or if they just tend to be in the [spec](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file) (and in practice). 

My sense is: let's support what BIDS does - so expect "Description" rather than "description". It would be great if we can validate the data dictionary with e.g. a jsonschema before we load it so we can tell the user if something is not correct (like the non-capitalized Description key).

**Comment by jarmoza** [comment]
Sounds like a new task in the making – in the very least converting the current default `'description'` into `'Description'`

**Comment by surchs** [comment]
Agree. Short term we should change all pre-defined keys (i.e. not user defined) to capitalized and then have a separate issue to discuss what to do about this more generally (i.e. validation, erroring when non-capitalized keys are given in the dictionary)

**Comment by rmanaem** [comment]
It was decided to implement validation for the uploaded data dictionary based on [pydantic models in CLI](https://github.com/neurobagel/bagel-cli/blob/main/bagel/dictionary_models.py), see #393
