### ISSUE TITLE
Phase 2 refactor: Adding getSelectedOption getter

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#377]
This previously unspecified getter retrieves the annotated value of a raw value in a particular column. Currently used by the `annot-categorical` component on its `vue-select`. These values are found in the store's `dataDictionary.annotated.<columnName>.valueMap` object.

In addition to the implementation of this getter with this task, I am going to go ahead and propose a name change to `getCategoricalSelectedOption` for specificity sake.

@surchs Let me know if you have any comment on the functionality or name change.

**Comment by surchs** [comment]
@jarmoza, how about `getSelectedCategoricalOption` as a name, that reads more clearly to me.

> getter retrieves the annotated value of a raw value in a particular column

That sounds perfect. I just want to point out that at the moment the (not yet existing) getter is being called with the row index of the table that is being displayed so that would have to be changed. I absolutely agree that the getter should accept the column and raw value, and not the row index.

**Comment by jarmoza** [comment]
@surchs Sounds good re: the name. 

>I just want to point out that at the moment the (not yet existing) getter is being called with the row index of the table that is >being displayed so that would have to be changed. I absolutely agree that the getter should accept the column and raw >value, and not the row index.

That's exactly how I've implemented it. PR coming up shortly.

**Comment by jarmoza** [comment]
Closed by #378
